import { db, naturesTable, itemsTable, movesTable } from "@workspace/db";

// ── Natures ──────────────────────────────────────────────────────────────────
const NATURES = [
  { name: "hardy",   displayName: "Hardy",   increasedStat: null,        decreasedStat: null },
  { name: "lonely",  displayName: "Lonely",  increasedStat: "attack",    decreasedStat: "defense" },
  { name: "brave",   displayName: "Brave",   increasedStat: "attack",    decreasedStat: "speed" },
  { name: "adamant", displayName: "Adamant", increasedStat: "attack",    decreasedStat: "specialAttack" },
  { name: "naughty", displayName: "Naughty", increasedStat: "attack",    decreasedStat: "specialDefense" },
  { name: "bold",    displayName: "Bold",    increasedStat: "defense",   decreasedStat: "attack" },
  { name: "docile",  displayName: "Docile",  increasedStat: null,        decreasedStat: null },
  { name: "relaxed", displayName: "Relaxed", increasedStat: "defense",   decreasedStat: "speed" },
  { name: "impish",  displayName: "Impish",  increasedStat: "defense",   decreasedStat: "specialAttack" },
  { name: "lax",     displayName: "Lax",     increasedStat: "defense",   decreasedStat: "specialDefense" },
  { name: "timid",   displayName: "Timid",   increasedStat: "speed",     decreasedStat: "attack" },
  { name: "hasty",   displayName: "Hasty",   increasedStat: "speed",     decreasedStat: "defense" },
  { name: "serious", displayName: "Serious", increasedStat: null,        decreasedStat: null },
  { name: "jolly",   displayName: "Jolly",   increasedStat: "speed",     decreasedStat: "specialAttack" },
  { name: "naive",   displayName: "Naive",   increasedStat: "speed",     decreasedStat: "specialDefense" },
  { name: "modest",  displayName: "Modest",  increasedStat: "specialAttack", decreasedStat: "attack" },
  { name: "mild",    displayName: "Mild",    increasedStat: "specialAttack", decreasedStat: "defense" },
  { name: "quiet",   displayName: "Quiet",   increasedStat: "specialAttack", decreasedStat: "speed" },
  { name: "bashful", displayName: "Bashful", increasedStat: null,        decreasedStat: null },
  { name: "rash",    displayName: "Rash",    increasedStat: "specialAttack", decreasedStat: "specialDefense" },
  { name: "calm",    displayName: "Calm",    increasedStat: "specialDefense", decreasedStat: "attack" },
  { name: "gentle",  displayName: "Gentle",  increasedStat: "specialDefense", decreasedStat: "defense" },
  { name: "sassy",   displayName: "Sassy",   increasedStat: "specialDefense", decreasedStat: "speed" },
  { name: "careful", displayName: "Careful", increasedStat: "specialDefense", decreasedStat: "specialAttack" },
  { name: "quirky",  displayName: "Quirky",  increasedStat: null,        decreasedStat: null },
];

// ── Held Items ────────────────────────────────────────────────────────────────
const HELD_ITEMS = [
  // Choice items
  { name: "choice-band",   displayName: "Choice Band",   category: "held-item", effect: "+50% Attack. Locked into one move." },
  { name: "choice-specs",  displayName: "Choice Specs",  category: "held-item", effect: "+50% Sp. Atk. Locked into one move." },
  { name: "choice-scarf",  displayName: "Choice Scarf",  category: "held-item", effect: "+50% Speed. Locked into one move." },
  // Power boosters
  { name: "life-orb",      displayName: "Life Orb",      category: "held-item", effect: "+30% damage on all moves. User loses 1/10 HP each time." },
  { name: "assault-vest",  displayName: "Assault Vest",  category: "held-item", effect: "+50% Sp. Def. Can only use damaging moves." },
  { name: "eviolite",      displayName: "Eviolite",      category: "held-item", effect: "+50% Def and Sp. Def for unevolved Pokémon." },
  // Berries
  { name: "sitrus-berry",  displayName: "Sitrus Berry",  category: "berry", effect: "Restores 25% HP when HP falls below 50%." },
  { name: "lum-berry",     displayName: "Lum Berry",     category: "berry", effect: "Cures any status condition once." },
  { name: "yache-berry",   displayName: "Yache Berry",   category: "berry", effect: "Halves damage from one super-effective Ice-type move." },
  { name: "chople-berry",  displayName: "Chople Berry",  category: "berry", effect: "Halves damage from one super-effective Fighting-type move." },
  { name: "haban-berry",   displayName: "Haban Berry",   category: "berry", effect: "Halves damage from one super-effective Dragon-type move." },
  { name: "wacan-berry",   displayName: "Wacan Berry",   category: "berry", effect: "Halves damage from one super-effective Electric-type move." },
  { name: "occa-berry",    displayName: "Occa Berry",    category: "berry", effect: "Halves damage from one super-effective Fire-type move." },
  { name: "passho-berry",  displayName: "Passho Berry",  category: "berry", effect: "Halves damage from one super-effective Water-type move." },
  { name: "rindo-berry",   displayName: "Rindo Berry",   category: "berry", effect: "Halves damage from one super-effective Grass-type move." },
  { name: "shuca-berry",   displayName: "Shuca Berry",   category: "berry", effect: "Halves damage from one super-effective Ground-type move." },
  { name: "coba-berry",    displayName: "Coba Berry",    category: "berry", effect: "Halves damage from one super-effective Flying-type move." },
  { name: "payapa-berry",  displayName: "Payapa Berry",  category: "berry", effect: "Halves damage from one super-effective Psychic-type move." },
  { name: "tanga-berry",   displayName: "Tanga Berry",   category: "berry", effect: "Halves damage from one super-effective Bug-type move." },
  { name: "charti-berry",  displayName: "Charti Berry",  category: "berry", effect: "Halves damage from one super-effective Rock-type move." },
  { name: "kasib-berry",   displayName: "Kasib Berry",   category: "berry", effect: "Halves damage from one super-effective Ghost-type move." },
  { name: "colbur-berry",  displayName: "Colbur Berry",  category: "berry", effect: "Halves damage from one super-effective Dark-type move." },
  { name: "babiri-berry",  displayName: "Babiri Berry",  category: "berry", effect: "Halves damage from one super-effective Steel-type move." },
  { name: "roseli-berry",  displayName: "Roseli Berry",  category: "berry", effect: "Halves damage from one super-effective Fairy-type move." },
  { name: "wiki-berry",    displayName: "Wiki Berry",    category: "berry", effect: "Restores 1/3 HP when HP is below 50%; confuses if -Sp. Atk nature." },
  { name: "figy-berry",    displayName: "Figy Berry",    category: "berry", effect: "Restores 1/3 HP when HP is below 50%; confuses if -Attack nature." },
  { name: "aguav-berry",   displayName: "Aguav Berry",   category: "berry", effect: "Restores 1/3 HP when HP is below 50%; confuses if -Sp. Def nature." },
  { name: "iapapa-berry",  displayName: "Iapapa Berry",  category: "berry", effect: "Restores 1/3 HP when HP is below 50%; confuses if -Defense nature." },
  { name: "mago-berry",    displayName: "Mago Berry",    category: "berry", effect: "Restores 1/3 HP when HP is below 50%; confuses if -Speed nature." },
  // Orbs & type-boosters
  { name: "dragon-fang",      displayName: "Dragon Fang",      category: "type-boost", effect: "+20% power to Dragon-type moves." },
  { name: "charcoal",         displayName: "Charcoal",         category: "type-boost", effect: "+20% power to Fire-type moves." },
  { name: "mystic-water",     displayName: "Mystic Water",     category: "type-boost", effect: "+20% power to Water-type moves." },
  { name: "magnet",           displayName: "Magnet",           category: "type-boost", effect: "+20% power to Electric-type moves." },
  { name: "miracle-seed",     displayName: "Miracle Seed",     category: "type-boost", effect: "+20% power to Grass-type moves." },
  { name: "nevermeltice",     displayName: "NeverMeltIce",     category: "type-boost", effect: "+20% power to Ice-type moves." },
  { name: "silk-scarf",       displayName: "Silk Scarf",       category: "type-boost", effect: "+20% power to Normal-type moves." },
  { name: "black-belt",       displayName: "Black Belt",       category: "type-boost", effect: "+20% power to Fighting-type moves." },
  { name: "sharp-beak",       displayName: "Sharp Beak",       category: "type-boost", effect: "+20% power to Flying-type moves." },
  { name: "poison-barb",      displayName: "Poison Barb",      category: "type-boost", effect: "+20% power to Poison-type moves." },
  { name: "soft-sand",        displayName: "Soft Sand",        category: "type-boost", effect: "+20% power to Ground-type moves." },
  { name: "hard-stone",       displayName: "Hard Stone",       category: "type-boost", effect: "+20% power to Rock-type moves." },
  { name: "silver-powder",    displayName: "Silver Powder",    category: "type-boost", effect: "+20% power to Bug-type moves." },
  { name: "spell-tag",        displayName: "Spell Tag",        category: "type-boost", effect: "+20% power to Ghost-type moves." },
  { name: "twisted-spoon",    displayName: "Twisted Spoon",    category: "type-boost", effect: "+20% power to Psychic-type moves." },
  { name: "metal-coat",       displayName: "Metal Coat",       category: "type-boost", effect: "+20% power to Steel-type moves." },
  { name: "fairy-feather",    displayName: "Fairy Feather",    category: "type-boost", effect: "+20% power to Fairy-type moves." },
  { name: "black-glasses",    displayName: "Black Glasses",    category: "type-boost", effect: "+20% power to Dark-type moves." },
  // Misc competitive items
  { name: "rocky-helmet",     displayName: "Rocky Helmet",     category: "held-item", effect: "Deals 1/6 HP damage to attacker on contact." },
  { name: "safety-goggles",   displayName: "Safety Goggles",   category: "held-item", effect: "Protects from powder moves and weather damage." },
  { name: "clear-amulet",     displayName: "Clear Amulet",     category: "held-item", effect: "Prevents stat reductions from opponent moves." },
  { name: "covert-cloak",     displayName: "Covert Cloak",     category: "held-item", effect: "Prevents secondary effects of moves from affecting the holder." },
  { name: "loaded-dice",      displayName: "Loaded Dice",      category: "held-item", effect: "Multi-hit moves always hit 4–5 times." },
  { name: "wide-lens",        displayName: "Wide Lens",        category: "held-item", effect: "+10% accuracy to all moves." },
  { name: "zoom-lens",        displayName: "Zoom Lens",        category: "held-item", effect: "+20% accuracy when moving after the target." },
  { name: "focus-sash",       displayName: "Focus Sash",       category: "held-item", effect: "Survive one hit from full HP that would KO. Single use." },
  { name: "focus-band",       displayName: "Focus Band",       category: "held-item", effect: "10% chance to survive a hit that would KO." },
  { name: "kings-rock",       displayName: "King's Rock",      category: "held-item", effect: "Moves have a 10% chance to cause flinch." },
  { name: "muscle-band",      displayName: "Muscle Band",      category: "held-item", effect: "+10% power to physical moves." },
  { name: "wise-glasses",     displayName: "Wise Glasses",     category: "held-item", effect: "+10% power to special moves." },
  { name: "expert-belt",      displayName: "Expert Belt",      category: "held-item", effect: "+20% power when landing super-effective moves." },
  { name: "metronome",        displayName: "Metronome",        category: "held-item", effect: "Boosts power each time the same move is used consecutively (up to 2x)." },
  { name: "adrenaline-orb",   displayName: "Adrenaline Orb",  category: "held-item", effect: "Boosts Speed by 1 stage when intimidated." },
  { name: "eject-button",     displayName: "Eject Button",     category: "held-item", effect: "Forces holder to switch out when hit by a move. Single use." },
  { name: "eject-pack",       displayName: "Eject Pack",       category: "held-item", effect: "Forces holder to switch out when a stat is lowered. Single use." },
  { name: "red-card",         displayName: "Red Card",         category: "held-item", effect: "When hit, forces the attacker to switch out. Single use." },
  { name: "blunder-policy",   displayName: "Blunder Policy",  category: "held-item", effect: "+2 Speed when a move misses. Single use." },
  { name: "throat-spray",     displayName: "Throat Spray",    category: "held-item", effect: "+1 Sp. Atk after using a sound-based move. Single use." },
  { name: "room-service",     displayName: "Room Service",    category: "held-item", effect: "-1 Speed when Trick Room is set. Single use." },
  { name: "power-herb",       displayName: "Power Herb",      category: "held-item", effect: "Charge moves (Solar Beam, Sky Attack, etc.) activate instantly. Single use." },
  { name: "white-herb",       displayName: "White Herb",      category: "held-item", effect: "Restores lowered stats to normal once. Single use." },
  { name: "mental-herb",      displayName: "Mental Herb",     category: "held-item", effect: "Cures infatuation, Taunt, Encore, Torment, Disable, Heal Block once." },
  { name: "leftovers",        displayName: "Leftovers",       category: "held-item", effect: "Restores 1/16 HP at end of each turn." },
  { name: "black-sludge",     displayName: "Black Sludge",    category: "held-item", effect: "Restores 1/16 HP for Poison-types; damages non-Poison-types each turn." },
  { name: "terrain-extender", displayName: "Terrain Extender", category: "held-item", effect: "Extends Terrain from 5 to 8 turns." },
  { name: "utility-umbrella", displayName: "Utility Umbrella", category: "held-item", effect: "Protects holder from effects of Rain and Sun (neither boosted nor dampened)." },
  { name: "protective-pads",  displayName: "Protective Pads", category: "held-item", effect: "Contact moves don't trigger the opponent's contact-based abilities." },
  { name: "punching-glove",   displayName: "Punching Glove",  category: "held-item", effect: "+10% power to punching moves; punching moves don't make contact." },
  { name: "booster-energy",   displayName: "Booster Energy",  category: "held-item", effect: "Activates Paradox Pokémon abilities (Protosynthesis/Quark Drive) without weather/terrain. Single use." },
  { name: "heavy-duty-boots", displayName: "Heavy-Duty Boots", category: "held-item", effect: "Holder is unaffected by entry hazards." },
  { name: "shed-shell",       displayName: "Shed Shell",      category: "held-item", effect: "Holder can always switch out or flee, even when trapped." },
  { name: "light-clay",       displayName: "Light Clay",      category: "held-item", effect: "Extends Reflect and Light Screen from 5 to 8 turns." },
  // Plates (type-specific Arceus, relevant for item database)
  { name: "weakness-policy",  displayName: "Weakness Policy", category: "held-item", effect: "+2 Atk and Sp. Atk when hit by a super-effective move. Single use." },
  { name: "air-balloon",      displayName: "Air Balloon",     category: "held-item", effect: "Holder is immune to Ground-type moves until popped by being hit." },
  { name: "flame-orb",        displayName: "Flame Orb",       category: "held-item", effect: "Burns the holder at end of turn." },
  { name: "toxic-orb",        displayName: "Toxic Orb",       category: "held-item", effect: "Badly poisons the holder at end of turn." },
];

// ── Mega Stones (Reg M-A legal) ───────────────────────────────────────────────
const MEGA_STONES = [
  { name: "venusaurite",    displayName: "Venusaurite",    category: "mega-stone", megaFor: "venusaur",    effect: "Allows Venusaur to Mega Evolve into Mega Venusaur." },
  { name: "charizardite-x", displayName: "Charizardite X", category: "mega-stone", megaFor: "charizard",   effect: "Allows Charizard to Mega Evolve into Mega Charizard X (Fire/Dragon)." },
  { name: "charizardite-y", displayName: "Charizardite Y", category: "mega-stone", megaFor: "charizard",   effect: "Allows Charizard to Mega Evolve into Mega Charizard Y (sets Drought)." },
  { name: "blastoisinite",  displayName: "Blastoisinite",  category: "mega-stone", megaFor: "blastoise",   effect: "Allows Blastoise to Mega Evolve into Mega Blastoise (Mega Launcher)." },
  { name: "beedrillite",    displayName: "Beedrillite",    category: "mega-stone", megaFor: "beedrill",    effect: "Allows Beedrill to Mega Evolve into Mega Beedrill (Adaptability, huge Speed)." },
  { name: "pidgeotite",     displayName: "Pidgeotite",     category: "mega-stone", megaFor: "pidgeot",     effect: "Allows Pidgeot to Mega Evolve into Mega Pidgeot (No Guard + Hurricane)." },
  { name: "clefablite",     displayName: "Clefablite",     category: "mega-stone", megaFor: "clefable",    effect: "Allows Clefable to Mega Evolve into Mega Clefable." },
  { name: "alakazite",      displayName: "Alakazite",      category: "mega-stone", megaFor: "alakazam",    effect: "Allows Alakazam to Mega Evolve into Mega Alakazam (Trace ability, huge Sp. Atk)." },
  { name: "victreebellite", displayName: "Victreebellite", category: "mega-stone", megaFor: "victreebel",  effect: "Allows Victreebel to Mega Evolve into Mega Victreebel." },
  { name: "slowbronite",    displayName: "Slowbronite",    category: "mega-stone", megaFor: "slowbro",     effect: "Allows Slowbro to Mega Evolve into Mega Slowbro (Shell Armor)." },
  { name: "gengarite",      displayName: "Gengarite",      category: "mega-stone", megaFor: "gengar",      effect: "Allows Gengar to Mega Evolve into Mega Gengar (Shadow Tag — traps opponents)." },
  { name: "kangaskhanite",  displayName: "Kangaskhanite",  category: "mega-stone", megaFor: "kangaskhan",  effect: "Allows Kangaskhan to Mega Evolve into Mega Kangaskhan (Parental Bond — hits twice)." },
  { name: "starmite",       displayName: "Starmite",       category: "mega-stone", megaFor: "starmie",     effect: "Allows Starmie to Mega Evolve into Mega Starmie." },
  { name: "pinsirite",      displayName: "Pinsirite",      category: "mega-stone", megaFor: "pinsir",      effect: "Allows Pinsir to Mega Evolve into Mega Pinsir (Aerilate — Normal moves become Flying)." },
  { name: "gyaradosite",    displayName: "Gyaradosite",    category: "mega-stone", megaFor: "gyarados",    effect: "Allows Gyarados to Mega Evolve into Mega Gyarados (Mold Breaker, becomes Dark/Water)." },
  { name: "aerodactylite",  displayName: "Aerodactylite",  category: "mega-stone", megaFor: "aerodactyl",  effect: "Allows Aerodactyl to Mega Evolve into Mega Aerodactyl (Tough Claws)." },
  { name: "dragonite-stone",displayName: "Dragonite Stone",category: "mega-stone", megaFor: "dragonite",   effect: "Allows Dragonite to Mega Evolve into Mega Dragonite." },
  { name: "meganite",       displayName: "Meganite",       category: "mega-stone", megaFor: "meganium",    effect: "Allows Meganium to Mega Evolve into Mega Meganium." },
  { name: "feraligatrite",  displayName: "Feraligatrite",  category: "mega-stone", megaFor: "feraligatr",  effect: "Allows Feraligatr to Mega Evolve into Mega Feraligatr (Sheer Force)." },
  { name: "ampharosite",    displayName: "Ampharosite",    category: "mega-stone", megaFor: "ampharos",    effect: "Allows Ampharos to Mega Evolve into Mega Ampharos (Mold Breaker, Electric/Dragon)." },
  { name: "steelixite",     displayName: "Steelixite",     category: "mega-stone", megaFor: "steelix",     effect: "Allows Steelix to Mega Evolve into Mega Steelix (Sand Force)." },
  { name: "scizorite",      displayName: "Scizorite",      category: "mega-stone", megaFor: "scizor",      effect: "Allows Scizor to Mega Evolve into Mega Scizor (Technician, huge bulk)." },
  { name: "heracronite",    displayName: "Heracronite",    category: "mega-stone", megaFor: "heracross",   effect: "Allows Heracross to Mega Evolve into Mega Heracross (Skill Link — multi-hit moves always hit 5×)." },
  { name: "skarmite",       displayName: "Skarmite",       category: "mega-stone", megaFor: "skarmory",    effect: "Allows Skarmory to Mega Evolve into Mega Skarmory." },
  { name: "houndoominite",  displayName: "Houndoominite",  category: "mega-stone", megaFor: "houndoom",    effect: "Allows Houndoom to Mega Evolve into Mega Houndoom (Solar Power)." },
  { name: "tyranitarite",   displayName: "Tyranitarite",   category: "mega-stone", megaFor: "tyranitar",   effect: "Allows Tyranitar to Mega Evolve into Mega Tyranitar (Sand Stream + massive Atk)." },
  { name: "gardevoirite",   displayName: "Gardevoirite",   category: "mega-stone", megaFor: "gardevoir",   effect: "Allows Gardevoir to Mega Evolve into Mega Gardevoir (Pixilate)." },
  { name: "sablenite",      displayName: "Sablenite",      category: "mega-stone", megaFor: "sableye",     effect: "Allows Sableye to Mega Evolve into Mega Sableye (Magic Bounce — reflects status moves)." },
  { name: "aggronite",      displayName: "Aggronite",      category: "mega-stone", megaFor: "aggron",      effect: "Allows Aggron to Mega Evolve into Mega Aggron (Filter, pure Steel-type)." },
  { name: "medichamite",    displayName: "Medichamite",    category: "mega-stone", megaFor: "medicham",    effect: "Allows Medicham to Mega Evolve into Mega Medicham (Pure Power — doubles Atk)." },
  { name: "manectite",      displayName: "Manectite",      category: "mega-stone", megaFor: "manectric",   effect: "Allows Manectric to Mega Evolve into Mega Manectric (Intimidate on Mega Evolution)." },
  { name: "sharpedonite",   displayName: "Sharpedonite",   category: "mega-stone", megaFor: "sharpedo",    effect: "Allows Sharpedo to Mega Evolve into Mega Sharpedo (Speed Boost)." },
  { name: "cameruptite",    displayName: "Cameruptite",    category: "mega-stone", megaFor: "camerupt",    effect: "Allows Camerupt to Mega Evolve into Mega Camerupt (Sheer Force)." },
  { name: "altarianite",    displayName: "Altarianite",    category: "mega-stone", megaFor: "altaria",     effect: "Allows Altaria to Mega Evolve into Mega Altaria (Pixilate, Dragon/Fairy)." },
  { name: "banettite",      displayName: "Banettite",      category: "mega-stone", megaFor: "banette",     effect: "Allows Banette to Mega Evolve into Mega Banette (Prankster)." },
  { name: "chimechonite",   displayName: "Chimechonite",   category: "mega-stone", megaFor: "chimecho",    effect: "Allows Chimecho to Mega Evolve into Mega Chimecho." },
  { name: "absolite",       displayName: "Absolite",       category: "mega-stone", megaFor: "absol",       effect: "Allows Absol to Mega Evolve into Mega Absol (Magic Bounce)." },
  { name: "glalitite",      displayName: "Glalitite",      category: "mega-stone", megaFor: "glalie",      effect: "Allows Glalie to Mega Evolve into Mega Glalie (Refrigerate)." },
  { name: "lopunnite",      displayName: "Lopunnite",      category: "mega-stone", megaFor: "lopunny",     effect: "Allows Lopunny to Mega Evolve into Mega Lopunny (Scrappy + Normalize-bypass)." },
  { name: "garchompite",    displayName: "Garchompite",    category: "mega-stone", megaFor: "garchomp",    effect: "Allows Garchomp to Mega Evolve into Mega Garchomp (Sand Force, loses Rough Skin)." },
  { name: "lucarionite",    displayName: "Lucarionite",    category: "mega-stone", megaFor: "lucario",     effect: "Allows Lucario to Mega Evolve into Mega Lucario (Adaptability — 145 Atk/140 SpAtk)." },
  { name: "abomasite",      displayName: "Abomasite",      category: "mega-stone", megaFor: "abomasnow",   effect: "Allows Abomasnow to Mega Evolve into Mega Abomasnow (Snow Warning + huge bulk)." },
  { name: "galladite",      displayName: "Galladite",      category: "mega-stone", megaFor: "gallade",     effect: "Allows Gallade to Mega Evolve into Mega Gallade (Inner Focus + huge Atk)." },
  { name: "frosslassite",   displayName: "Frosslassite",   category: "mega-stone", megaFor: "froslass",    effect: "Allows Froslass to Mega Evolve into Mega Froslass." },
  { name: "emboarite",      displayName: "Emboarite",      category: "mega-stone", megaFor: "emboar",      effect: "Allows Emboar to Mega Evolve into Mega Emboar." },
  { name: "excadrillite",   displayName: "Excadrillite",   category: "mega-stone", megaFor: "excadrill",   effect: "Allows Excadrill to Mega Evolve into Mega Excadrill." },
  { name: "audinite",       displayName: "Audinite",       category: "mega-stone", megaFor: "audino",      effect: "Allows Audino to Mega Evolve into Mega Audino (Healer)." },
  { name: "chandelurite",   displayName: "Chandelurite",   category: "mega-stone", megaFor: "chandelure",  effect: "Allows Chandelure to Mega Evolve into Mega Chandelure." },
  { name: "golurkit",       displayName: "Golurkit",       category: "mega-stone", megaFor: "golurk",      effect: "Allows Golurk to Mega Evolve into Mega Golurk." },
  { name: "chesnaughtite",  displayName: "Chesnaughtite",  category: "mega-stone", megaFor: "chesnaught",  effect: "Allows Chesnaught to Mega Evolve into Mega Chesnaught." },
  { name: "delphoxite",     displayName: "Delphoxite",     category: "mega-stone", megaFor: "delphox",     effect: "Allows Delphox to Mega Evolve into Mega Delphox." },
  { name: "greninjaite",    displayName: "Greninjaite",    category: "mega-stone", megaFor: "greninja",    effect: "Allows Greninja to Mega Evolve into Mega Greninja." },
  { name: "floettite",      displayName: "Floettite",      category: "mega-stone", megaFor: "floette",     effect: "Allows Floette to Mega Evolve into Mega Floette." },
  { name: "meowstite",      displayName: "Meowstite",      category: "mega-stone", megaFor: "meowstic",    effect: "Allows Meowstic to Mega Evolve into Mega Meowstic." },
  { name: "hawluchite",     displayName: "Hawluchite",     category: "mega-stone", megaFor: "hawlucha",    effect: "Allows Hawlucha to Mega Evolve into Mega Hawlucha." },
  { name: "crabomite",      displayName: "Crabomite",      category: "mega-stone", megaFor: "crabominable",effect: "Allows Crabominable to Mega Evolve into Mega Crabominable." },
  { name: "drampite",       displayName: "Drampite",       category: "mega-stone", megaFor: "drampa",      effect: "Allows Drampa to Mega Evolve into Mega Drampa." },
  { name: "scovillainite",  displayName: "Scovillainite",  category: "mega-stone", megaFor: "scovillain",  effect: "Allows Scovillain to Mega Evolve into Mega Scovillain." },
  { name: "glimmorite",     displayName: "Glimmorite",     category: "mega-stone", megaFor: "glimmora",    effect: "Allows Glimmora to Mega Evolve into Mega Glimmora." },
];

// ── Moves (top VGC moves) ─────────────────────────────────────────────────────
const MOVES = [
  // Physical
  { name: "close-combat",    displayName: "Close Combat",    type: "fighting", category: "physical", power: 120, accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "-1 Def and Sp. Def after use." },
  { name: "drain-punch",     displayName: "Drain Punch",     type: "fighting", category: "physical", power: 75,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Heals 50% of damage dealt." },
  { name: "ice-punch",       displayName: "Ice Punch",       type: "ice",      category: "physical", power: 75,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "30% chance to freeze." },
  { name: "thunder-punch",   displayName: "Thunder Punch",   type: "electric", category: "physical", power: 75,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "30% chance to paralyze." },
  { name: "fire-punch",      displayName: "Fire Punch",      type: "fire",     category: "physical", power: 75,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "30% chance to burn." },
  { name: "earthquake",      displayName: "Earthquake",      type: "ground",   category: "physical", power: 100, accuracy: 100, pp: 10, priority: 0, target: "all-adjacent",    description: "Hits all adjacent Pokémon. Ignores ally." },
  { name: "rock-slide",      displayName: "Rock Slide",      type: "rock",     category: "physical", power: 75,  accuracy: 90,  pp: 10, priority: 0, target: "all-opponents",   description: "30% chance to flinch. Hits both opponents." },
  { name: "iron-head",       displayName: "Iron Head",       type: "steel",    category: "physical", power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "30% chance to flinch." },
  { name: "play-rough",      displayName: "Play Rough",      type: "fairy",    category: "physical", power: 90,  accuracy: 90,  pp: 10, priority: 0, target: "single",         description: "10% chance to lower Attack." },
  { name: "knock-off",       displayName: "Knock Off",       type: "dark",     category: "physical", power: 65,  accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Removes held item. 1.5× power if target holds an item." },
  { name: "sucker-punch",    displayName: "Sucker Punch",    type: "dark",     category: "physical", power: 70,  accuracy: 100, pp: 5,  priority: 1, target: "single",         description: "Priority +1. Fails if target isn't using a damaging move." },
  { name: "extreme-speed",   displayName: "Extreme Speed",   type: "normal",   category: "physical", power: 80,  accuracy: 100, pp: 5,  priority: 2, target: "single",         description: "Priority +2." },
  { name: "fake-out",        displayName: "Fake Out",        type: "normal",   category: "physical", power: 40,  accuracy: 100, pp: 10, priority: 3, target: "single",         description: "Priority +3. Flinches target. Only works on first turn." },
  { name: "u-turn",          displayName: "U-turn",          type: "bug",      category: "physical", power: 70,  accuracy: 100, pp: 20, priority: 0, target: "single",         description: "User switches out after hitting." },
  { name: "ice-shard",       displayName: "Ice Shard",       type: "ice",      category: "physical", power: 40,  accuracy: 100, pp: 30, priority: 1, target: "single",         description: "Priority +1." },
  { name: "aqua-jet",        displayName: "Aqua Jet",        type: "water",    category: "physical", power: 40,  accuracy: 100, pp: 20, priority: 1, target: "single",         description: "Priority +1." },
  { name: "bullet-punch",    displayName: "Bullet Punch",    type: "steel",    category: "physical", power: 40,  accuracy: 100, pp: 30, priority: 1, target: "single",         description: "Priority +1." },
  { name: "mach-punch",      displayName: "Mach Punch",      type: "fighting", category: "physical", power: 40,  accuracy: 100, pp: 30, priority: 1, target: "single",         description: "Priority +1." },
  { name: "shadow-sneak",    displayName: "Shadow Sneak",    type: "ghost",    category: "physical", power: 40,  accuracy: 100, pp: 30, priority: 1, target: "single",         description: "Priority +1." },
  { name: "crunch",          displayName: "Crunch",          type: "dark",     category: "physical", power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "20% chance to lower Defense." },
  { name: "outrage",         displayName: "Outrage",         type: "dragon",   category: "physical", power: 120, accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Lasts 2–3 turns. Confuses user after." },
  { name: "high-horsepower", displayName: "High Horsepower", type: "ground",   category: "physical", power: 95,  accuracy: 95,  pp: 10, priority: 0, target: "single",         description: "Strong Ground move with good accuracy." },
  { name: "body-press",      displayName: "Body Press",      type: "fighting", category: "physical", power: 80,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Uses Defense instead of Attack for damage calculation." },
  { name: "gyro-ball",       displayName: "Gyro Ball",       type: "steel",    category: "physical", power: null,accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Power increases as user's Speed is lower than target's." },
  { name: "heavy-slam",      displayName: "Heavy Slam",      type: "steel",    category: "physical", power: null,accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Power based on weight difference (max 120)." },
  { name: "stomping-tantrum",displayName: "Stomping Tantrum",type: "ground",   category: "physical", power: 75,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Power doubles if previous move failed." },
  { name: "superpower",      displayName: "Superpower",      type: "fighting", category: "physical", power: 120, accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "-1 Atk and Def after use." },
  { name: "zen-headbutt",    displayName: "Zen Headbutt",    type: "psychic",  category: "physical", power: 80,  accuracy: 90,  pp: 15, priority: 0, target: "single",         description: "20% chance to flinch." },
  { name: "wood-hammer",     displayName: "Wood Hammer",     type: "grass",    category: "physical", power: 120, accuracy: 100, pp: 15, priority: 0, target: "single",         description: "User takes 1/3 recoil damage." },
  { name: "flare-blitz",     displayName: "Flare Blitz",     type: "fire",     category: "physical", power: 120, accuracy: 100, pp: 15, priority: 0, target: "single",         description: "33% recoil. 10% chance to burn." },
  { name: "waterfall",       displayName: "Waterfall",       type: "water",    category: "physical", power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "20% chance to flinch." },
  { name: "double-edge",     displayName: "Double-Edge",     type: "normal",   category: "physical", power: 120, accuracy: 100, pp: 15, priority: 0, target: "single",         description: "33% recoil damage." },
  { name: "return",          displayName: "Return",          type: "normal",   category: "physical", power: 102, accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Power based on friendship (max 102 at max friendship)." },
  { name: "facade",          displayName: "Facade",          type: "normal",   category: "physical", power: 70,  accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Power doubles to 140 when user is burned, paralyzed, or poisoned." },
  { name: "pin-missile",     displayName: "Pin Missile",     type: "bug",      category: "physical", power: 25,  accuracy: 95,  pp: 20, priority: 0, target: "single",         description: "Hits 2–5 times. With Skill Link/Loaded Dice, always hits 5×." },
  { name: "bullet-seed",     displayName: "Bullet Seed",     type: "grass",    category: "physical", power: 25,  accuracy: 100, pp: 30, priority: 0, target: "single",         description: "Hits 2–5 times. With Skill Link/Loaded Dice, always hits 5×." },
  { name: "icicle-spear",    displayName: "Icicle Spear",    type: "ice",      category: "physical", power: 25,  accuracy: 100, pp: 30, priority: 0, target: "single",         description: "Hits 2–5 times. With Skill Link/Loaded Dice, always hits 5×." },
  { name: "population-bomb", displayName: "Population Bomb", type: "normal",   category: "physical", power: 20,  accuracy: 90,  pp: 10, priority: 0, target: "single",         description: "Hits 1–10 times. With Loaded Dice, hits 4–10 times." },
  { name: "wicked-blow",     displayName: "Wicked Blow",     type: "dark",     category: "physical", power: 75,  accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Always lands a critical hit." },
  { name: "surging-strikes", displayName: "Surging Strikes", type: "water",    category: "physical", power: 25,  accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Hits exactly 3 times. Each hit is a critical hit." },
  { name: "glaive-rush",     displayName: "Glaive Rush",     type: "dragon",   category: "physical", power: 120, accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Next move against user always hits and deals double damage." },
  { name: "jet-punch",       displayName: "Jet Punch",       type: "water",    category: "physical", power: 60,  accuracy: 100, pp: 15, priority: 1, target: "single",         description: "Priority +1. Palafin's signature move." },
  { name: "tera-blast",      displayName: "Tera Blast",      type: "normal",   category: "physical", power: 80,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Changes type to Tera type. Uses higher of Atk/SpAtk. If Tera, may be physical or special." },
  // Special
  { name: "moonblast",       displayName: "Moonblast",       type: "fairy",    category: "special",  power: 95,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "30% chance to lower Sp. Atk." },
  { name: "dazzling-gleam",  displayName: "Dazzling Gleam",  type: "fairy",    category: "special",  power: 80,  accuracy: 100, pp: 10, priority: 0, target: "all-opponents",   description: "Hits both opponents." },
  { name: "shadow-ball",     displayName: "Shadow Ball",     type: "ghost",    category: "special",  power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "20% chance to lower Sp. Def." },
  { name: "psyshock",        displayName: "Psyshock",        type: "psychic",  category: "special",  power: 80,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Uses target's Defense instead of Sp. Def." },
  { name: "psychic",         displayName: "Psychic",         type: "psychic",  category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "10% chance to lower Sp. Def." },
  { name: "hyper-voice",     displayName: "Hyper Voice",     type: "normal",   category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "all-opponents",   description: "Hits both opponents. Sound move — bypasses Substitute." },
  { name: "discharge",       displayName: "Discharge",       type: "electric", category: "special",  power: 80,  accuracy: 100, pp: 15, priority: 0, target: "all-adjacent",    description: "30% chance to paralyze. Hits all adjacent." },
  { name: "thunderbolt",     displayName: "Thunderbolt",     type: "electric", category: "special",  power: 90,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "10% chance to paralyze." },
  { name: "thunder",         displayName: "Thunder",         type: "electric", category: "special",  power: 110, accuracy: 70,  pp: 10, priority: 0, target: "single",         description: "100% accuracy in Rain. 30% paralyze." },
  { name: "flamethrower",    displayName: "Flamethrower",    type: "fire",     category: "special",  power: 90,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "10% chance to burn." },
  { name: "fire-blast",      displayName: "Fire Blast",      type: "fire",     category: "special",  power: 110, accuracy: 85,  pp: 5,  priority: 0, target: "single",         description: "10% chance to burn." },
  { name: "heat-wave",       displayName: "Heat Wave",       type: "fire",     category: "special",  power: 95,  accuracy: 90,  pp: 10, priority: 0, target: "all-opponents",   description: "Hits both opponents. 10% burn." },
  { name: "surf",            displayName: "Surf",            type: "water",    category: "special",  power: 90,  accuracy: 100, pp: 15, priority: 0, target: "all-adjacent",    description: "Hits all adjacent Pokémon." },
  { name: "hydro-pump",      displayName: "Hydro Pump",      type: "water",    category: "special",  power: 110, accuracy: 80,  pp: 5,  priority: 0, target: "single",         description: "High power, imperfect accuracy." },
  { name: "ice-beam",        displayName: "Ice Beam",        type: "ice",      category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "10% chance to freeze." },
  { name: "blizzard",        displayName: "Blizzard",        type: "ice",      category: "special",  power: 110, accuracy: 70,  pp: 5,  priority: 0, target: "all-opponents",   description: "100% accuracy in Snow/Hail. 10% freeze. Hits both." },
  { name: "energy-ball",     displayName: "Energy Ball",     type: "grass",    category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "10% chance to lower Sp. Def." },
  { name: "solar-beam",      displayName: "Solar Beam",      type: "grass",    category: "special",  power: 120, accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Charges first turn; no charge needed in Sun." },
  { name: "pollen-puff",     displayName: "Pollen Puff",     type: "bug",      category: "special",  power: 90,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "Heals ally 50% HP if targeting ally. Damages foe." },
  { name: "sludge-bomb",     displayName: "Sludge Bomb",     type: "poison",   category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "30% chance to poison." },
  { name: "sludge-wave",     displayName: "Sludge Wave",     type: "poison",   category: "special",  power: 95,  accuracy: 100, pp: 10, priority: 0, target: "all-adjacent",    description: "10% chance to poison. Hits all adjacent." },
  { name: "dark-pulse",      displayName: "Dark Pulse",      type: "dark",     category: "special",  power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "20% chance to flinch." },
  { name: "aura-sphere",     displayName: "Aura Sphere",     type: "fighting", category: "special",  power: 80,  accuracy: null, pp: 20, priority: 0, target: "single",         description: "Never misses." },
  { name: "focus-blast",     displayName: "Focus Blast",     type: "fighting", category: "special",  power: 120, accuracy: 70,  pp: 5,  priority: 0, target: "single",         description: "10% chance to lower Sp. Def." },
  { name: "draco-meteor",    displayName: "Draco Meteor",    type: "dragon",   category: "special",  power: 130, accuracy: 90,  pp: 5,  priority: 0, target: "single",         description: "-2 Sp. Atk after use." },
  { name: "dragon-pulse",    displayName: "Dragon Pulse",    type: "dragon",   category: "special",  power: 85,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Reliable Dragon special move." },
  { name: "earth-power",     displayName: "Earth Power",     type: "ground",   category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "10% chance to lower Sp. Def." },
  { name: "lava-plume",      displayName: "Lava Plume",      type: "fire",     category: "special",  power: 80,  accuracy: 100, pp: 15, priority: 0, target: "all-adjacent",    description: "30% chance to burn. Hits all adjacent." },
  { name: "overheat",        displayName: "Overheat",        type: "fire",     category: "special",  power: 130, accuracy: 90,  pp: 5,  priority: 0, target: "single",         description: "-2 Sp. Atk after use." },
  { name: "bug-buzz",        displayName: "Bug Buzz",        type: "bug",      category: "special",  power: 90,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "10% chance to lower Sp. Def. Sound move." },
  { name: "leaf-storm",      displayName: "Leaf Storm",      type: "grass",    category: "special",  power: 130, accuracy: 90,  pp: 5,  priority: 0, target: "single",         description: "-2 Sp. Atk after use." },
  { name: "spore",           displayName: "Spore",           type: "grass",    category: "status",   power: null,accuracy: 100, pp: 15, priority: 0, target: "single",         description: "Puts target to sleep. Always hits." },
  { name: "gunk-shot",       displayName: "Gunk Shot",       type: "poison",   category: "physical", power: 120, accuracy: 80,  pp: 5,  priority: 0, target: "single",         description: "30% chance to poison." },
  { name: "mystical-fire",   displayName: "Mystical Fire",   type: "fire",     category: "special",  power: 75,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Always lowers target's Sp. Atk by 1." },
  { name: "expanding-force", displayName: "Expanding Force", type: "psychic",  category: "special",  power: 80,  accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Power ×1.5 and hits both opponents in Psychic Terrain." },
  { name: "rising-voltage",  displayName: "Rising Voltage",  type: "electric", category: "special",  power: 70,  accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Power doubles in Electric Terrain." },
  { name: "misty-explosion", displayName: "Misty Explosion", type: "fairy",    category: "special",  power: 100, accuracy: 100, pp: 5,  priority: 0, target: "all-adjacent",    description: "User faints. Power ×1.5 in Misty Terrain. Hits all adjacent." },
  { name: "collision-course",displayName: "Collision Course",type: "fighting", category: "physical", power: 100, accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Power ×1.3 when super-effective." },
  { name: "electro-drift",   displayName: "Electro Drift",   type: "electric", category: "special",  power: 100, accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Power ×1.3 when super-effective." },
  // Status
  { name: "trick-room",      displayName: "Trick Room",      type: "psychic",  category: "status",   power: null,accuracy: null,pp: 5,  priority: -7,target: "field",          description: "Reverses move order (slowest first) for 5 turns. Priority -7." },
  { name: "tailwind",        displayName: "Tailwind",        type: "flying",   category: "status",   power: null,accuracy: null,pp: 15, priority: 0, target: "ally-team",       description: "Doubles Speed of user's team for 4 turns." },
  { name: "protect",         displayName: "Protect",         type: "normal",   category: "status",   power: null,accuracy: null,pp: 10, priority: 4, target: "self",            description: "Priority +4. Protects from all moves that turn." },
  { name: "wide-guard",      displayName: "Wide Guard",      type: "rock",     category: "status",   power: null,accuracy: null,pp: 10, priority: 3, target: "ally-team",       description: "Priority +3. Protects whole team from spread moves." },
  { name: "quick-guard",     displayName: "Quick Guard",     type: "fighting", category: "status",   power: null,accuracy: null,pp: 15, priority: 3, target: "ally-team",       description: "Priority +3. Protects whole team from priority moves." },
  { name: "follow-me",       displayName: "Follow Me",       type: "normal",   category: "status",   power: null,accuracy: null,pp: 20, priority: 2, target: "self",            description: "Priority +2. Redirects all single-target moves to user." },
  { name: "rage-powder",     displayName: "Rage Powder",     type: "bug",      category: "status",   power: null,accuracy: null,pp: 20, priority: 2, target: "self",            description: "Priority +2. Redirects single-target moves to user. Doesn't affect Grass-types or Safety Goggles." },
  { name: "helping-hand",    displayName: "Helping Hand",    type: "normal",   category: "status",   power: null,accuracy: null,pp: 20, priority: 5, target: "ally",            description: "Priority +5. Boosts adjacent ally's move power by 50%." },
  { name: "taunt",           displayName: "Taunt",           type: "dark",     category: "status",   power: null,accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Target can only use damaging moves for 3 turns." },
  { name: "encore",          displayName: "Encore",          type: "normal",   category: "status",   power: null,accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Forces target to repeat its last move for 3 turns." },
  { name: "will-o-wisp",     displayName: "Will-O-Wisp",     type: "fire",     category: "status",   power: null,accuracy: 85,  pp: 15, priority: 0, target: "single",         description: "Burns the target." },
  { name: "toxic",           displayName: "Toxic",           type: "poison",   category: "status",   power: null,accuracy: 90,  pp: 10, priority: 0, target: "single",         description: "Badly poisons the target." },
  { name: "thunder-wave",    displayName: "Thunder Wave",    type: "electric", category: "status",   power: null,accuracy: 90,  pp: 20, priority: 0, target: "single",         description: "Paralyzes the target." },
  { name: "sleep-powder",    displayName: "Sleep Powder",    type: "grass",    category: "status",   power: null,accuracy: 75,  pp: 15, priority: 0, target: "single",         description: "Puts target to sleep." },
  { name: "perish-song",     displayName: "Perish Song",     type: "normal",   category: "status",   power: null,accuracy: null,pp: 5,  priority: 0, target: "all",            description: "All Pokémon on field faint after 3 turns." },
  { name: "sunny-day",       displayName: "Sunny Day",       type: "fire",     category: "status",   power: null,accuracy: null,pp: 5,  priority: 0, target: "field",          description: "Sets harsh sunlight for 5 turns (8 with Heat Rock)." },
  { name: "rain-dance",      displayName: "Rain Dance",      type: "water",    category: "status",   power: null,accuracy: null,pp: 5,  priority: 0, target: "field",          description: "Sets Rain for 5 turns (8 with Damp Rock)." },
  { name: "sandstorm",       displayName: "Sandstorm",       type: "rock",     category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "field",          description: "Sets Sandstorm for 5 turns (8 with Smooth Rock)." },
  { name: "snowscape",       displayName: "Snowscape",       type: "ice",      category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "field",          description: "Sets Snow for 5 turns (8 with Icy Rock). Raises Ice-type evasion." },
  { name: "reflect",         displayName: "Reflect",         type: "psychic",  category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "ally-team",       description: "Halves physical damage to team for 5 turns (8 with Light Clay)." },
  { name: "light-screen",    displayName: "Light Screen",    type: "psychic",  category: "status",   power: null,accuracy: null,pp: 30, priority: 0, target: "ally-team",       description: "Halves special damage to team for 5 turns (8 with Light Clay)." },
  { name: "aurora-veil",     displayName: "Aurora Veil",     type: "ice",      category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "ally-team",       description: "Halves all damage to team for 5 turns. Requires Snow/Hail to use." },
  { name: "instruct",        displayName: "Instruct",        type: "psychic",  category: "status",   power: null,accuracy: null,pp: 15, priority: 0, target: "single",         description: "Target immediately uses its last move again." },
  { name: "quiver-dance",    displayName: "Quiver Dance",    type: "bug",      category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "self",            description: "+1 Sp. Atk, Sp. Def, and Speed." },
  { name: "swords-dance",    displayName: "Swords Dance",    type: "normal",   category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "self",            description: "+2 Attack." },
  { name: "nasty-plot",      displayName: "Nasty Plot",      type: "dark",     category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "self",            description: "+2 Sp. Atk." },
  { name: "calm-mind",       displayName: "Calm Mind",       type: "psychic",  category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "self",            description: "+1 Sp. Atk and Sp. Def." },
  { name: "dragon-dance",    displayName: "Dragon Dance",    type: "dragon",   category: "status",   power: null,accuracy: null,pp: 20, priority: 0, target: "self",            description: "+1 Attack and Speed." },
  { name: "growl",           displayName: "Growl",           type: "normal",   category: "status",   power: null,accuracy: 100, pp: 40, priority: 0, target: "all-opponents",   description: "-1 Attack to all opponents." },
  { name: "intimidate",      displayName: "Feather Dance",   type: "flying",   category: "status",   power: null,accuracy: 100, pp: 15, priority: 0, target: "single",         description: "-2 Attack." },
  { name: "recover",         displayName: "Recover",         type: "normal",   category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "self",            description: "Restores 50% max HP." },
  { name: "roost",           displayName: "Roost",           type: "flying",   category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "self",            description: "Restores 50% HP. User loses Flying type that turn." },
  { name: "substitute",      displayName: "Substitute",      type: "normal",   category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "self",            description: "Creates a decoy using 25% max HP." },
  { name: "imprison",        displayName: "Imprison",        type: "psychic",  category: "status",   power: null,accuracy: null,pp: 10, priority: 0, target: "self",            description: "Prevents opponents from using moves known by the user." },
  { name: "encore",          displayName: "Encore",          type: "normal",   category: "status",   power: null,accuracy: 100, pp: 5,  priority: 0, target: "single",         description: "Forces opponent to repeat last used move for 3 turns." },
  { name: "disable",         displayName: "Disable",         type: "normal",   category: "status",   power: null,accuracy: 100, pp: 20, priority: 0, target: "single",         description: "Disables last move used by target for 4 turns." },
  { name: "trick",           displayName: "Trick",           type: "psychic",  category: "status",   power: null,accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Swaps held items with target." },
  { name: "switcheroo",      displayName: "Switcheroo",      type: "dark",     category: "status",   power: null,accuracy: 100, pp: 10, priority: 0, target: "single",         description: "Swaps held items with target." },
  { name: "swagger",         displayName: "Swagger",         type: "normal",   category: "status",   power: null,accuracy: 85,  pp: 15, priority: 0, target: "single",         description: "+2 Attack, but confuses target." },
  { name: "electro-web",     displayName: "Electro Web",     type: "electric", category: "special",  power: 55,  accuracy: 95,  pp: 15, priority: 0, target: "all-opponents",   description: "-1 Speed to all opponents. Good for speed control." },
  { name: "icy-wind",        displayName: "Icy Wind",        type: "ice",      category: "special",  power: 55,  accuracy: 95,  pp: 15, priority: 0, target: "all-opponents",   description: "-1 Speed to all opponents." },
  { name: "bulldoze",        displayName: "Bulldoze",        type: "ground",   category: "physical", power: 60,  accuracy: 100, pp: 20, priority: 0, target: "all-adjacent",    description: "-1 Speed to all adjacent Pokémon including allies." },
  { name: "lunge",           displayName: "Lunge",           type: "bug",      category: "physical", power: 80,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "-1 Attack to target." },
  { name: "snarl",           displayName: "Snarl",           type: "dark",     category: "special",  power: 55,  accuracy: 95,  pp: 15, priority: 0, target: "all-opponents",   description: "-1 Sp. Atk to both opponents." },
  { name: "spirit-break",    displayName: "Spirit Break",    type: "fairy",    category: "physical", power: 75,  accuracy: 100, pp: 15, priority: 0, target: "single",         description: "-1 Sp. Atk to target." },
  { name: "breaking-swipe",  displayName: "Breaking Swipe",  type: "dragon",   category: "physical", power: 60,  accuracy: 100, pp: 15, priority: 0, target: "all-opponents",   description: "-1 Attack to both opponents." },
];

async function seed() {
  console.log("Seeding natures...");
  await db.insert(naturesTable).values(NATURES).onConflictDoNothing();
  console.log(`Inserted ${NATURES.length} natures.`);

  console.log("Seeding items (held items + mega stones)...");
  const allItems = [
    ...HELD_ITEMS.map((i) => ({ ...i, megaFor: null, spriteUrl: null, description: null })),
    ...MEGA_STONES.map((i) => ({ ...i, spriteUrl: null, description: null })),
  ];
  await db.insert(itemsTable).values(allItems).onConflictDoNothing();
  console.log(`Inserted ${allItems.length} items.`);

  console.log("Seeding moves...");
  const uniqueMoves = MOVES.filter((m, i, arr) => arr.findIndex((n) => n.name === m.name) === i);
  await db.insert(movesTable).values(uniqueMoves).onConflictDoNothing();
  console.log(`Inserted ${uniqueMoves.length} moves.`);

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
