import { Router } from "express";

const router = Router();

export const archetypes = [
  {
    id: "trick-room",
    name: "Trick Room",
    description: "Sets up Trick Room to make the slowest Pokémon move first, enabling slow but powerful attackers to sweep. Especially dangerous in Reg M-A since many eligible Pokémon have high Attack but low Speed.",
    category: "control",
    coreStrategy: "Set Trick Room with Hatterene, Cofagrigus, or Reuniclus. Then sweep with slow powerhouses like Conkeldurr, Mega Kangaskhan, Mega Meganium, Golurk, or Mamoswine. Oranguru provides Instruct for extra pressure. Mega Slowbro walls and attacks under TR.",
    keyPokemon: ["hatterene","cofagrigus","conkeldurr","reuniclus","mega-kangaskhan","mega-meganium","golurk","mamoswine","slowbro"],
    strengths: ["Neutralizes fast sweepers and hyper offense", "Slow tanks become dominant offensive threats", "Mega Kangaskhan is oppressive under TR", "Hard to reverse once established", "Wide pool of slow powerhouses in Reg M-A"],
    weaknesses: ["Taunt shuts down all TR setters", "Only lasts 5 turns — requires resetting", "Priority moves still go first", "Ghost-types bypass Normal TR sweepers", "Imprison counters the whole strategy"],
    counterplay: "Taunt the setter before TR goes up. Use priority moves like Fake Out on the setter. Bring your own TR user for a speed tie. Ghost-types dodge Normal-type TR sweepers.",
    dangerLevel: 9,
  },
  {
    id: "rain",
    name: "Rain",
    description: "Politoed sets permanent Rain. Swift Swim attackers double their Speed and blast through teams with boosted Water moves. Mega Gyarados, Araquanid, and Mega Feraligatr are premier rain threats.",
    category: "weather",
    coreStrategy: "Politoed sets auto-Rain with Drizzle. Mega Gyarados becomes a monstrous mixed attacker. Araquanid hits absurdly hard with Water Bubble. Mega Feraligatr Swords Dances and sweeps. Toxapex walls and sets Toxic under Rain. Thunder has 100% accuracy.",
    keyPokemon: ["politoed","mega-gyarados","araquanid","mega-feraligatr","toxapex","pelipper"],
    strengths: ["Massive Water move power boost", "Swift Swim doubles Speed in Rain", "Thunder never misses in Rain", "Mega Gyarados is a top-tier threat with Mold Breaker", "Araquanid's Water Bubble triples Water damage effectively"],
    weaknesses: ["Weak to opposing weather especially Sun and Sand", "Grass and Electric types wall the team", "If Politoed faints early, the strategy collapses", "Predictable team structure — opponents prepare for it"],
    counterplay: "Bring Torkoal or a Sun setter to override Rain. Grass-types like Tsareena and Whimsicott resist Water. Electric moves shred the team. Target Politoed first to remove auto-rain.",
    dangerLevel: 8,
  },
  {
    id: "sun",
    name: "Sun",
    description: "Torkoal sets auto-Sun with Drought. Chlorophyll users like Mega Venusaur double in Speed. Mega Charizard Y's Drought replaces Torkoal entirely and hits harder than almost anything in the format.",
    category: "weather",
    coreStrategy: "Mega Charizard Y sets its own Drought and hits with absurdly powered Fire Blast. Or run Torkoal for double-weather with Venusaur. Roserade and other Grass Chlorophyll users are blazing fast. Growth raises both Attack and Sp.Atk by 2 in Sun. Solar Beam needs no charge.",
    keyPokemon: ["charizard","torkoal","venusaur","roserade","mega-charizard-y","mega-venusaur"],
    strengths: ["Mega Charizard Y sets its own Sun and hits like a truck", "Chlorophyll doubles Speed of Grass and some others", "Solar Beam is free in Sun", "Growth is +2/+2 in Sun", "Venusaur's thick fat halves Fire and Ice damage"],
    weaknesses: ["Rock Slide and Rock-type moves absolutely shred Charizard", "Water moves punish Fire-types hard", "Torkoal is extremely slow and frail", "Opposing weather shuts the strategy down"],
    counterplay: "Rock Slide threatens Charizard every turn. Water moves punish Fire-types. Override Sun with Rain or Sand. Sand chips Venusaur every turn.",
    dangerLevel: 8,
  },
  {
    id: "sand",
    name: "Sand",
    description: "Tyranitar sets permanent Sand with Sand Stream, giving it +50% Sp.Def. Excadrill becomes a Sand Rush monster. Hippowdon offers a bulkier alternate setter. Sand chips all non-Rock/Ground/Steel types.",
    category: "weather",
    coreStrategy: "Tyranitar or Hippowdon sets Sand. Excadrill with Sand Rush doubles Speed and wrecks teams with Iron Head and Earthquake. Mega Tyranitar is even more dominant — massive bulk and power. Garchomp and Gliscor thrive in sand. Toxic stall from Hippowdon grinds opponents down.",
    keyPokemon: ["tyranitar","mega-tyranitar","excadrill","hippowdon","garchomp","gliscor"],
    strengths: ["Chip damage every turn from Sand", "Mega Tyranitar has incredible bulk and power", "Sand Rush Excadrill is an elite sweeper", "Rock-type special defense buff for Tyranitar is massive", "Garchomp fits perfectly alongside"],
    weaknesses: ["Ice and Fighting wreck the core Pokémon", "Water moves threaten multiple members", "Opposing weather cancels Sand", "Sand chips your own non-Rock/Ground/Steel members"],
    counterplay: "Ice Beam and Ice Punch threaten Garchomp and Gliscor. Fighting moves like Drain Punch punish Tyranitar. Override Sand with Rain. Target Excadrill before it gets Sand Rush going.",
    dangerLevel: 8,
  },
  {
    id: "mega-offense",
    name: "Mega Offense",
    description: "Reg M-A exclusive — abuse the Mega Evolution system to field the single most powerful boosted threat possible alongside a support core. One Mega Evolution per battle means every team must choose wisely.",
    category: "offense",
    coreStrategy: "Choose a single dominant Mega — Mega Kangaskhan (Parental Bond doubles hits), Mega Garchomp (Sand Force + huge base power), Mega Gengar (Shadow Tag trapps), Mega Lucario (Adaptability), Mega Heracross (Skill Link + Pin Missile), or Mega Tyranitar. Build five supporting Pokémon around protecting and enabling that one Mega.",
    keyPokemon: ["mega-kangaskhan","mega-garchomp","mega-gengar","mega-lucario","mega-heracross","mega-tyranitar"],
    strengths: ["Mega Kangaskhan's Parental Bond breaks Focus Sash and deals massive chip", "Shadow Tag Mega Gengar traps specific threats and removes them", "Mega Heracross with Skill Link Pin Missile is absurd damage", "Mega Lucario hits 145/140 Atk/SpAtk with Adaptability Close Combat", "One Mega means the opponent must predict which one you're using"],
    weaknesses: ["Only one Mega Evolution per battle — must commit early or lose the window", "If your Mega goes down early, you lose your main win condition", "Opponents can pivot away from the Mega's coverage", "Item-less non-Mega members lose to item-dependent matchups"],
    counterplay: "KO or cripple the Mega before it Mega Evolves. Fake Out prevents first-turn Mega aggression. Intimidate chains reduce physical Mega damage. Identify which Mega they're running from team preview and prepare specifically.",
    dangerLevel: 10,
  },
  {
    id: "perish-trap",
    name: "Perish Trap",
    description: "Mega Gengar uses Shadow Tag to trap opponents, then Perish Song forces all on-field Pokémon to faint after 3 turns. Nearly impossible to escape once activated.",
    category: "control",
    coreStrategy: "Mega Gengar's Shadow Tag prevents opponents from switching out. Perish Song starts a 3-turn countdown. Team then stalls with Protect and redirectors. Mismagius, Hatterene, or Spiritomb assist with Perish Song spreading. Dragapult provides speed control and Ghost coverage.",
    keyPokemon: ["mega-gengar","mismagius","hatterene","spiritomb","dragapult","whimsicott"],
    strengths: ["Shadow Tag guarantees no switches — targets are trapped immediately", "Perish Song forces guaranteed KOs in 3 turns", "Nearly impossible to counter once set up", "Extremely strong vs defensive stall teams", "Gengar's great Speed means it often moves first"],
    weaknesses: ["Ghost-types cannot be trapped by Shadow Tag", "Taunt on Gengar shuts down Perish Song", "Very setup-dependent — one bad turn collapses it", "Gengar is frail and can be KO'd before it acts", "Requires knowing the opponent can't escape"],
    counterplay: "Bring a Ghost-type — they cannot be trapped. Taunt Gengar before it can use Perish Song. Target and KO Gengar immediately — it is frail. Dark-type moves threaten Gengar easily.",
    dangerLevel: 9,
  },
  {
    id: "bulky-offense",
    name: "Bulky Offense",
    description: "The most consistent archetype — pair offensive threats with supportive utility. Incineroar + Hatterene or Whimsicott form the backbone of most balanced Reg M-A teams.",
    category: "balance",
    coreStrategy: "Incineroar provides Fake Out, Intimidate, and Knock Off. Hatterene brings Misty Surge and supportive coverage. Whimsicott provides Tailwind and Prankster priority. Toxapex walls physical threats. Dragapult or Mega Charizard Y provides offensive pressure. Oranguru supplies Instruct for double moves.",
    keyPokemon: ["incineroar","hatterene","whimsicott","toxapex","dragapult","oranguru"],
    strengths: ["Incineroar's Intimidate + Fake Out is universally powerful", "Misty Terrain from Hatterene blocks status", "Extremely consistent across best-of-3", "Flexible — adapts to multiple threats", "Hard to teamwipe against solid defensive core"],
    weaknesses: ["Lacks the explosive power of Mega Offense or pure HO", "Slower pace means TR can flip matchups", "Predictable Incineroar core is well prepared for", "No hard win condition — must outplay turn by turn"],
    counterplay: "Knock Off targets Incineroar's Sitrus Berry. Pollen Puff bypasses Hatterene's Misty Terrain protection. Target and KO Hatterene to open status moves. Taunt shuts down Whimsicott's Tailwind.",
    dangerLevel: 7,
  },
  {
    id: "tailwind",
    name: "Tailwind Offense",
    description: "Sets Tailwind to double team Speed for 4 turns, enabling powerful mid-speed attackers to outrun everything. Talonflame's Gale Wings gives guaranteed Tailwind priority on turn 1.",
    category: "offense",
    coreStrategy: "Talonflame uses Gale Wings to guarantee Tailwind goes up on turn 1, even against faster opponents. Whimsicott with Prankster also provides priority Tailwind. Then sweep with Mega Garchomp, Mega Lucario, Mega Heracross, Dragapult, or Volcarona.",
    keyPokemon: ["talonflame","whimsicott","mega-garchomp","mega-lucario","volcarona","dragapult"],
    strengths: ["Talonflame's Gale Wings makes Tailwind guaranteed turn 1", "Doubles team Speed for 4 turns — hugely impactful", "Volcarona under Tailwind hits hard with Quiver Dance access", "Mega Garchomp at effectively doubled Speed is devastating", "Combos well with Mega Evolutions"],
    weaknesses: ["Only lasts 4 turns — very short window", "Rock Slide and Stealth Rock punish Talonflame", "Taunt stops Talonflame and Whimsicott", "After Tailwind expires, speed control is gone"],
    counterplay: "Fake Out Talonflame on turn 1 to prevent Tailwind. Rock Slide threatens the entire Flying side. Taunt stops both Tailwind setters. After 4 turns, the team loses speed control — stall it out.",
    dangerLevel: 8,
  },
  {
    id: "stall",
    name: "Stall and Pressure",
    description: "Uses Toxapex, Mega Sableye, and defensive walls to slowly chip opponents with Toxic, Burn, and residual damage while healing with Recover and Protect cycling.",
    category: "defense",
    coreStrategy: "Mega Sableye's Magic Bounce reflects status moves back and prevents hazards. Toxapex walls physical attackers and spreads Toxic. Milotic's Marvel Scale + Recover creates an unkillable wall. Spiritomb provides Will-O-Wisp for burns. Gliscor and Hippowdon sponge attacks and apply pressure.",
    keyPokemon: ["mega-sableye","toxapex","milotic","spiritomb","gliscor","hippowdon"],
    strengths: ["Mega Sableye reflects every status move back — shuts down Toxic/Burn/Sleep strategies", "Toxapex survives almost everything and poisons reliably", "Milotic with Recover is extremely hard to KO", "Burns cripple physical attackers", "Extremely hard to break without specific coverage"],
    weaknesses: ["Loses badly to strong Mega attackers who don't care about status", "Taunt shuts down all stall moves", "VGC format's limited turns means stall is less effective than singles", "Trick Room stall is fast enough to break through", "Loses to clock pressure if the opponent forces a timer win"],
    counterplay: "Taunt shuts down stall entirely. Strong Mega attackers that self-Recover or ignore status break through. Knock Off removes Leftovers and Shields. Force the clock — stall loses on timer if you're ahead.",
    dangerLevel: 6,
  },
];

router.get("/archetypes", (_req, res) => {
  res.json(archetypes);
});

export default router;
