import { Router } from "express";

const router = Router();

export const archetypes = [
  {
    id: "trick-room",
    name: "Trick Room",
    description: "A team that sets up Trick Room to make the slowest Pokemon move first, enabling powerful but slow attackers to sweep.",
    category: "weather-setter",
    coreStrategy: "Set Trick Room with a bulky Psychic-type setter (Porygon2, Mimikyu, Hatterene, Indeedee-F), then sweep with slow high-Attack Pokemon like Ursaluna, Iron Hands, or Amoonguss.",
    keyPokemon: ["ursaluna", "hatterene", "porygon2", "iron-hands", "indeedee", "amoonguss"],
    strengths: ["Ignores fast-paced hyper offense", "Extremely hard to stop once set up", "Slow Pokemon become oppressive", "Weather teams often too slow to outspeed your sweepers under TR"],
    weaknesses: ["Taunt shuts down setters", "TR has limited turns (5)", "Fast Taunt users destroy the setup", "Priority moves bypass Trick Room speed advantage", "Very weak to Imprison"],
    counterplay: "Use Taunt or Imprison (copying Trick Room) to prevent setup. Priority moves like Fake Out still go first. Try to KO the setter before it can set TR.",
    dangerLevel: 8,
  },
  {
    id: "rain",
    name: "Rain",
    description: "Sets up Rain to boost Water-type moves and enable Swift Swim/Drizzle interactions. Extremely fast and powerful under rain.",
    category: "weather",
    coreStrategy: "Pelipper or Politoed sets automatic Rain. Swift Swim users like Barraskewda, Araquanid, or Ludicolo become extremely fast and hit hard with boosted Water moves. Kingdra fills a similar role.",
    keyPokemon: ["pelipper", "barraskewda", "araquanid", "palafin", "kingdra", "ludicolo"],
    strengths: ["High damage output from Water moves", "Swift Swim doubles Speed in rain", "Thunder has 100% accuracy in rain", "Very consistent offense", "Palafin-Hero is a threat with boosted Jet Punch"],
    weaknesses: ["Loses badly if weather is changed", "Most members weak to Electric", "Predictable team structure", "Grass-types resist Water and exploit the team"],
    counterplay: "Bring your own weather setter to override Rain. Grass-types like Rillaboom wall Water moves. Electric-types threaten Pelipper. Sun overwrites Rain and makes Water weaker.",
    dangerLevel: 8,
  },
  {
    id: "sun",
    name: "Sun",
    description: "Sets up harsh sunlight to boost Fire-type moves and enable Chlorophyll Speed boosts on Grass-type sweepers.",
    category: "weather",
    coreStrategy: "Torkoal or Drought users set Sun. Venusaur and Lilligant double in speed under Chlorophyll. Fire Blast from Charizard or Volcanion hits absurdly hard under Sun. Solar Beam requires no charge turn.",
    keyPokemon: ["torkoal", "venusaur", "lilligant-hisui", "charizard", "volcanion", "flutter-mane"],
    strengths: ["Very high Fire-type damage", "Chlorophyll users are blazing fast", "Solar Beam without charge under Sun", "Growth boosts Attack and Sp.Atk by 2 stages in Sun"],
    weaknesses: ["Torkoal is extremely slow and frail to attack", "Water moves rain-check the team — water types stop it cold", "Rock and Ground types threaten Fire-types", "Opposing weather ends the strategy"],
    counterplay: "Set your own weather to override Sun. Rock-type moves threaten Charizard. Water-types like Politoed can flip the weather advantage. Torkoal must be targeted first.",
    dangerLevel: 7,
  },
  {
    id: "sand",
    name: "Sand",
    description: "Summons a sandstorm that chips non-Rock/Ground/Steel types every turn, while giving Rock-types a special defense boost.",
    category: "weather",
    coreStrategy: "Tyranitar or Hippowdon set perpetual sand. Rock-types like Tyranitar get +50% SpDef. Excadrill becomes extremely fast in sand with Sand Rush. Landorus-Therian and Ground/Rock attackers dominate.",
    keyPokemon: ["tyranitar", "hippowdon", "excadrill", "landorus-therian", "garchomp", "iron-thorns"],
    strengths: ["Residual damage every turn pressures opponents", "Rock-types gain massive special bulk", "Excadrill with Sand Rush is a menacing sweeper", "Tyranitar has insane natural bulk"],
    weaknesses: ["Ice and Fighting types destroy the core", "Weather override ruins the strategy", "Many VGC teams carry counters due to Tyranitar's popularity", "Steel-types wall Ground moves"],
    counterplay: "Use Ice or Fighting moves to threaten Tyranitar. Override weather with Rain or Sun. Intimidate chains reduce Excadrill's physical output significantly.",
    dangerLevel: 7,
  },
  {
    id: "snow",
    name: "Snow",
    description: "Sets Snow (Hail's replacement) to give Ice-type Pokemon an evasion boost and enable Aurora Veil.",
    category: "weather",
    coreStrategy: "Abomasnow or Cetitan set Snow. Aurora Veil halves all damage for 5 turns (8 with Icy Rock). Ice-types like Baxcalibur, Chien-Pao, and Cetitan become extremely tanky behind Veil. Blizzard never misses in Snow.",
    keyPokemon: ["abomasnow", "baxcalibur", "chien-pao", "cetitan", "ninetales-alola", "flutter-mane"],
    strengths: ["Aurora Veil from Abomasnow/Ninetales-Alola provides incredible team bulk", "Blizzard is a reliable spread move in Snow", "Baxcalibur with Glaive Rush hits absurdly hard", "Ice Shard priority with Chien-Pao"],
    weaknesses: ["Ice-types have many weaknesses (Fire, Rock, Steel, Fighting)", "Fire and Steel moves demolish Snow setters", "Veil expires after 5 turns", "Rock Slide hits multiple common Snow team members"],
    counterplay: "Bring Rock Slide for spread damage against Ice-types. Fire-type moves pressure Abomasnow. Override Snow with Sun. Brick Break cancels Aurora Veil instantly.",
    dangerLevel: 7,
  },
  {
    id: "hyper-offense",
    name: "Hyper Offense",
    description: "A glass cannon team with maximum offensive pressure and minimal defensive play — attack before getting attacked.",
    category: "offense",
    coreStrategy: "Stack offensive threats with coverage moves, speed control (Tailwind, Electro Web), and screen support. Teams often run 4-6 offensive threats with no defensive pivots. Tera types enable surprise type coverage. Win through raw damage before the opponent can set up.",
    keyPokemon: ["flutter-mane", "iron-hands", "chien-pao", "roaring-moon", "chi-yu", "iron-valiant"],
    strengths: ["Extremely fast pace denies opponent setup", "Can overwhelm defensive teams with raw damage", "Tera types hide offensive coverage", "Strong lead options against most archetypes"],
    weaknesses: ["Trick Room completely reverses the speed advantage", "Weak to Intimidate chains", "One bad prediction can collapse the entire team", "Lacks defensive options if early game goes wrong"],
    counterplay: "Set up Trick Room to neutralize speed. Intimidate users like Incineroar soften physical attackers. Defensive pivots like Amoonguss can redirect and chip away. Tailwind timer creates decision pressure.",
    dangerLevel: 9,
  },
  {
    id: "perish-trap",
    name: "Perish Trap",
    description: "Uses Perish Song to force KOs on all Pokemon in play, then traps them with Shadow Tag or Arena Trap to prevent switching out.",
    category: "control",
    coreStrategy: "Gothitelle or Gengar use Shadow Tag to trap opponents. Perish Song counts down from 3 — any Pokemon still on field after 3 turns faints. Team then stalls until the count hits 0, usually with Protect spam, Substitute, or redirection. Mismagius is a common Perish Song + Substitute user.",
    keyPokemon: ["gothitelle", "mismagius", "smeargle", "amoonguss", "incineroar", "indeedee"],
    strengths: ["Forces guaranteed KOs on trapped opponents", "Almost impossible to stop once fully set up", "Counters defensive stall teams", "Psychic Seed + Indeedee combo prevents TR interference"],
    weaknesses: ["Only works if opponent can't switch out (Shadow Tag required)", "Takes multiple turns to execute — risky against fast offense", "Easily disrupted by Taunt", "Requires very specific Pokemon (Gothitelle is niche)", "Ghost-types are immune to trapping"],
    counterplay: "Bring a Ghost-type — they cannot be trapped. Taunt stops Perish Song and Protect. Target Gothitelle immediately before Shadow Tag is activated. Use your own redirection to keep a sacrificial Pokemon on field.",
    dangerLevel: 8,
  },
  {
    id: "bulky-offense",
    name: "Bulky Offense",
    description: "A balanced team with both offensive pressure and defensive pivots — the most consistent meta archetype.",
    category: "balance",
    coreStrategy: "Pair offensive threats with supportive utility Pokemon like Incineroar (Fake Out, Intimidate), Amoonguss (Rage Powder, Spore), and Follow Me users. Ting-Lu provides entry hazards and mixed defense. Team maintains offensive pressure while having defensive answers to threats.",
    keyPokemon: ["incineroar", "amoonguss", "ting-lu", "urshifu-rapid-strike", "flutter-mane", "landorus-therian"],
    strengths: ["Consistent across the entire tournament", "Can adapt to multiple threats", "Incineroar + Amoonguss support is almost universally good", "Strong in a best-of-3 format since it's hard to teamwipe"],
    weaknesses: ["Lacks the raw power of hyper offense", "Slower pace means Trick Room can flip games", "Predictable core lets opponents prepare specific counters", "No hard win condition — relies on outplaying opponent turn by turn"],
    counterplay: "Knock Off removes Incineroar's Sitrus Berry. Pollen Puff bypasses Rage Powder redirect. Target and KO Amoonguss early to remove spore threat. Taunt shuts down Ting-Lu's utility moves.",
    dangerLevel: 7,
  },
  {
    id: "tailwind",
    name: "Tailwind Offense",
    description: "Sets up Tailwind to double the team's Speed for 4 turns, enabling slower powerful attackers to outspeed everything.",
    category: "offense",
    coreStrategy: "Fast Tailwind setters like Talonflame, Koraidon, or Murkrow set up Tailwind. Powerful attackers then move at double speed. Often combined with spread moves and high base power coverage. Talonflame's Gale Wings gives it Tailwind priority.",
    keyPokemon: ["talonflame", "murkrow", "koraidon", "flutter-mane", "iron-valiant", "chi-yu"],
    strengths: ["Doubles speed of entire team for 4 turns", "Can outspeed Trick Room responses", "Talonflame's Gale Wings sets Tailwind turn 1 even against faster opponents", "Combined with strong attackers = devastating"],
    weaknesses: ["Only lasts 4 turns — short window", "Rock Slide and Electric moves threaten Talonflame", "Losing the Tailwind setter early loses the strategy", "Taunt on the setter prevents Tailwind"],
    counterplay: "Priority Fake Out on Talonflame prevents Tailwind on turn 1. Rock Slide threatens Flying-types. After Tailwind expires, the team may lose speed control. Trick Room can reverse the advantage midgame.",
    dangerLevel: 8,
  },
];

router.get("/archetypes", (req, res) => {
  res.json(archetypes);
});

export default router;
